main: kernitus.plugin.Hotels.HotelsMain
name: Hotels
version: 0.4.2
author: kernitus
description: Allows the making of hotels and renting of rooms.
website: http://www.spigotmc.org/resources/hotels.2047/
load: POSTWORLD

depend: [Vault, WorldEdit, WorldGuard]

commands:
  Hotels:
   description: Hotels's main command
   aliases: ht
   permission: hotels.*
   permission-message: You do not have permission!

permissions:
   hotels.*:
     description: Gives access to all Hotels commands
     children:
       hotels.createmode: true
       hotels.create: true
       hotels.delete: true
       hotels.delete.rooms: true
       hotels.rename: true
       hotels.renumber: true
       hotels.remove: true
       hotels.check: true
       hotels.check.others: true
       hotels.sign.create: true
       hotels.sign.use: true
       hotels.list.hotels: true
       hotels.list.rooms: true
       hotels.friend: true
   hotels.createmode:
     description: Allows you to enter hotel creation mode
     default: op
   hotels.create:
     description: Allows you to create a hotel
     default: op
   hotels.delete:
     description: Allows you to delete hotels and connected rooms and signs
     default: op
   hotels.delete.rooms:
     description: Allows you to delete hotel rooms and connected signs
     default: op
   hotels.rename:
     description: Allows you to rename hotels and connected rooms and signs
     default: op
   hotels.renumber:
     description: Allows you to renumber rooms and connected signs
     default: op
   hotels.remove:
     description: Allows you to remove a player as a renter of a room
     default: op
   hotels.check:
     description: Allows you to see stats about your rented rooms
     default: true
   hotels.check.others:
     description: Allows you to see stats about other player's rented rooms
     default: op
   hotels.sign.create:
     description: Allows you to create hotel room signs
     default: op
   hotels.sign.use:
     description: Allows you to use hotel room signs
     default: true
   hotels.list.hotels:
     description: Allows you to see a list of all hotels
     default: true
   hotels.list.rooms:
     description: Allows you to see a list of all rooms within a hotel
     default: op
   hotels.friend:
     description: Allows you to add and remove friends from rented rooms
     default: true
