main: kernitus.plugin.Hotels.HotelsMain
name: Hotels
version: 1.1.2
author: kernitus
description: Allows the making of hotels and renting of rooms.
website: http://www.spigotmc.org/resources/hotels.2047/
load: POSTWORLD

depend: [Vault, WorldEdit, WorldGuard]

commands:
  Hotels:
   description: Hotels's main command
   aliases: ht
  Room:
   description: Point at sign to create room sign

permissions:
   hotels.*:
     description: Gives access to all Hotels functions
     children:
       hotels.sign.use: true
       hotels.remove: true
       hotels.rent: true
       hotels.check: true
       hotels.check.others: true
       hotels.list.hotels: true
       hotels.list.rooms: true
       hotels.friend: true
       hotels.reload: true
       hotels.createmode.user: true
       hotels.create.user: true
       hotels.sign.create.user: true
       hotels.delete.user: true
       hotels.delete.rooms.user: true
       hotels.home.user: true
       hotels.sethome.user: true
       hotels.rename.user: true
       hotels.renumber.user: true
       hotels.createmode.admin: true
       hotels.create.admin: true
       hotels.sign.create.admin: true
       hotels.delete.admin: true
       hotels.delete.rooms.admin: true
       hotels.home.admin: true
       hotels.sethome.admin: true
       hotels.rename.admin: true
       hotels.renumber.admin: true
       hotels.sell.hotel: true
       hotels.sell.room: true
       hotels.buy.room: true
       hotels.reset.toggle: true
       hotels.reset.reset: true


   hotels.sign.use:
     description: Allows you to use hotel room signs
     default: true
   hotels.remove:
     description: Allows you to remove a player as a renter of a room
     default: op
   hotels.rent:
     description: Allows you to rent rooms through command
     default: true
   hotels.check:
     description: Allows you to see stats about your rented rooms
     default: true
   hotels.check.others:
     description: Allows you to see stats about other player's rented rooms
     default: op
   hotels.list.hotels:
     description: Allows you to see a list of all hotels
     default: true
   hotels.list.rooms:
     description: Allows you to see a list of all rooms within a hotel
     default: true 
   hotels.friend:
     description: Allows you to add and remove friends from rented rooms
     default: true
   hotels.reload:
     description: Allows you to reload all configuration files
     default: op
   hotels.createmode.user:
     description: Allows you to enter hotel creation mode
     default: true
   hotels.createmode.admin:
     description: Allows you to enter hotel creation mode
     default: op
   hotels.create.user:
     description: Allows you to create a hotel
     default: true
   hotels.create.admin:
     description: Allows you to create a hotel
     default: op
   hotels.sign.create.user:
     description: Allows you to create hotel room signs
     default: true
   hotels.sign.create:
     description: Allows you to create hotel room signs
     default: op    
   hotels.delete.user:
     description: Allows you to delete hotels and connected rooms and signs
     default: true   
   hotels.delete.admin:
     description: Allows you to delete hotels and connected rooms and signs
     default: op     
   hotels.delete.rooms.user:
     description: Allows you to delete hotel rooms and connected signs
     default: true   
   hotels.delete.rooms.admin:
     description: Allows you to delete hotel rooms and connected signs
     default: op     
   hotels.home.user:
     description: Allows you to teleport to hotel and room homes
     default: true 
   hotels.home.admin:
     description: Allows you to teleport to hotel and room homes
     default: op     
   hotels.sethome.user:
     description: Allows you to set hotel homes if in creation mode and user room homes
     default: true  
   hotels.sethome.admin:
     description: Allows you to set hotel homes if in creation mode and user room homes
     default: op 
   hotels.rename.user:
     description: Allows you to rename hotels and connected rooms and signs
     default: true
   hotels.rename.admin:
     description: Allows you to rename hotels and connected rooms and signs
     default: op
   hotels.renumber.user:
     description: Allows you to renumber rooms and connected signs
     default: true
   hotels.renumber.admin:
     description: Allows you to renumber rooms and connected signs
     default: op
   hotels.sell.hotel:
     description: Allows you to sell your hotels
     default: true
   hotels.sell.room:
     description: Allows you to sell rooms
     default: true
   hotels.buy.room:
     description: Allows you to buy rooms
     default: true
   hotels.reset.toggle:
     description: Allows you to toggle resetting of specific rooms upon unrenting
     default: op
   hotels.reset.reset:
     description: Allows you to reset a room
     default: op
