main: kernitus.plugin.Hotels.HotelsMain
name: Hotels
version: 1.0
author: kernitus
description: Allows the making of hotels and renting of rooms.
website: http://dev.bukkit.org/bukkit-plugins/hotels/
load: POSTWORLD

depend: [Vault, WorldEdit, WorldGuard]
softdepend: [BarAPI]

commands:
  Hotels:
   description: Hotels's main command
   permission: hotels.*
   permission-message: You do not have permission

permissions:
   hotels.*:
     description: Gives access to all Hotels commands
     children:
       hotels.createmode: true
       hotels.create: true
       hotels.check: true
       hotels.check.others: true
   hotels.createmode:
     description: Allows you to ender hotel creation mode
     default: op
   hotels.create:
     description: Allows you to create a hotel
     default: op
   hotels.check:
     description: Allows you to see stats about your rented rooms
     default: true
   hotels.check.others:
     description: Allows you to see stats about other player's rented rooms
     default: op